In [27]:
import numpy as np 

In [28]:
Psi = np.array([0,1,1,0])/np.sqrt(2)

In [29]:
A0 = np.array([ [ 1, 0 ], [0, 1] ])
A1 = np.array([ [ 1, 1 ], [1, -1] ])/np.sqrt(2)

In [30]:
B0 = np.array([ [ 1-np.sqrt(2), 1+np.sqrt(2) ], [1, 1] ])
B0 = B0 / np.linalg.norm(B0,axis=0)

B1 = np.array([ [ -1-np.sqrt(2), -1+np.sqrt(2) ], [1, 1] ])
B1 = B1 / np.linalg.norm(B1,axis=0)
B0, B1 

(array([[-0.38268343,  0.92387953],
        [ 0.92387953,  0.38268343]]),
 array([[-0.92387953,  0.38268343],
        [ 0.38268343,  0.92387953]]))

In [31]:
p_bell = np.zeros((4,2,2))

In [32]:
p_bell[:,0,0] = np.abs( np.kron(A0,B0)@Psi  )**2
p_bell[:,0,1] = np.abs( np.kron(A0,B1)@Psi  )**2
p_bell[:,1,0] = np.abs( np.kron(A1,B0)@Psi  )**2
p_bell[:,1,1] = np.abs( np.kron(A1,B1)@Psi  )**2

In [40]:
p_bell/4

array([[[0.10669417, 0.01830583],
        [0.01830583, 0.01830583]],

       [[0.01830583, 0.10669417],
        [0.10669417, 0.10669417]],

       [[0.01830583, 0.10669417],
        [0.10669417, 0.10669417]],

       [[0.10669417, 0.01830583],
        [0.01830583, 0.01830583]]])

In [38]:
p_bell[0,0,0]/4,  p_bell[3,0,0]/4, p_bell[0,0,1]/4

(0.10669417382415916, 0.10669417382415919, 0.01830582617584078)

In [34]:
(2+np.sqrt(2))/32 

0.10669417382415922

In [35]:
(2-np.sqrt(2))/32 

0.018305826175840777