In [161]:
import numpy as np
import matplotlib.pyplot as plt 

Primero definimos las mediciones. Sean $\{A_0,A_1 \}$ los observables de Alice y $\{B_0, B_1\}$ los de Bob. Sea $\{ |a_{ij}\rangle\}$ los autoestados de los observables $\{A_l\}$ y $\{ |b_{ij}\rangle\}$ los de $\{B_m\}$. Así 
$$ M[0,l,k,:]= |a_{lk}\rangle \quad \text{y}  \quad M[1,m,k',:]= |b_{mk'}\rangle.$$ 

In [162]:
M = np.zeros( (2,2,2,2) )
# indices Alice(0) or Bob(1), Obs 0 o 1, autovec 0 o 1, largo del vector

In [163]:
M[0,1,:,:] = np.array([  [1, 0], [0, 1]  ]) #Z
M[0,0,:,:] = np.array([  [1, 1], [1, -1]  ])/np.sqrt(2) #X

In [164]:
M[1,0,0,:] = np.array([1-np.sqrt(2), 1])/np.sqrt( 2*(2-np.sqrt(2)) )  #X+Z
M[1,0,1,:] = np.array([1+np.sqrt(2), 1])/np.sqrt( 2*(2+np.sqrt(2)) )

M[1,1,0,:] = np.array([-1-np.sqrt(2), 1])/np.sqrt( 2*(2+np.sqrt(2)) )
M[1,1,1,:] = np.array([-1+np.sqrt(2), 1])/np.sqrt( 2*(2-np.sqrt(2)) ) #X-Z

In [165]:
M

array([[[[ 0.70710678,  0.70710678],
         [ 0.70710678, -0.70710678]],

        [[ 1.        ,  0.        ],
         [ 0.        ,  1.        ]]],


       [[[-0.38268343,  0.92387953],
         [ 0.92387953,  0.38268343]],

        [[-0.92387953,  0.38268343],
         [ 0.38268343,  0.92387953]]]])

Ahora calcularemos la distribución de probabilidad
$$ P(klk'mij) = \frac{1}{4} P_{Bell}(kk'|lm)\delta_{li}\delta_{mj},$$
con
$$ P_{Bell}(kk'|lm) = Tr [ \rho |a_{lk}\rangle\langle a_{lk}|\otimes |b_{mk'}\rangle\langle b_{mk'}| ]. $$

In [166]:
probs_triangle = np.zeros( (2,2,2,2,2,2) )
Psi_ab = np.array([ 0, 1, -1, 0 ])/np.sqrt(2)

for k in range(2):
    for kk in range(2):
        for l in range(2):
            for m in range(2):
                measure = np.kron( M[0,l,k,:], M[1,m,kk,:] )  
                probs_triangle[ l, k, m, kk, l, m ] = 0.25 * np.abs( np.vdot( measure, Psi_ab ) )**2 

In [167]:
probs_triangle

array([[[[[[0.10669417, 0.        ],
           [0.        , 0.        ]],

          [[0.01830583, 0.        ],
           [0.        , 0.        ]]],


         [[[0.        , 0.10669417],
           [0.        , 0.        ]],

          [[0.        , 0.01830583],
           [0.        , 0.        ]]]],



        [[[[0.01830583, 0.        ],
           [0.        , 0.        ]],

          [[0.10669417, 0.        ],
           [0.        , 0.        ]]],


         [[[0.        , 0.01830583],
           [0.        , 0.        ]],

          [[0.        , 0.10669417],
           [0.        , 0.        ]]]]],




       [[[[[0.        , 0.        ],
           [0.10669417, 0.        ]],

          [[0.        , 0.        ],
           [0.01830583, 0.        ]]],


         [[[0.        , 0.        ],
           [0.        , 0.01830583]],

          [[0.        , 0.        ],
           [0.        , 0.10669417]]]],



        [[[[0.        , 0.        ],
           [0.01830583, 0.     

Podemos ver que las distribución de probabilidad $P$ coincide con la distribución de Fritz.

In [168]:
(2+np.sqrt(2))/32, (2-np.sqrt(2))/32 

(0.10669417382415922, 0.018305826175840777)

In [169]:
index_plus = np.where( np.isclose( probs_triangle, (2+np.sqrt(2))/32 ) ) 
index_string = [ 'l ', 'k ', 'm ', "k'", 'i ', 'j ' ]

for I in range(6):
    print( index_string[I]+'=', index_plus[I] )

l = [0 0 0 0 1 1 1 1]
k = [0 0 1 1 0 0 1 1]
m = [0 1 0 1 0 1 0 1]
k'= [0 0 1 1 0 1 1 0]
i = [0 0 0 0 1 1 1 1]
j = [0 1 0 1 0 1 0 1]


In [170]:
index_plus = np.where( np.isclose( probs_triangle, (2-np.sqrt(2))/32 ) ) 
index_string = [ 'l ', 'k ', 'm ', "k'", 'i ', 'j ' ]
for I in range(6):
    print( index_string[I]+'=', index_plus[I] )

l = [0 0 0 0 1 1 1 1]
k = [0 0 1 1 0 0 1 1]
m = [0 1 0 1 0 1 0 1]
k'= [1 1 0 0 1 0 0 1]
i = [0 0 0 0 1 1 1 1]
j = [0 1 0 1 0 1 0 1]


Calculemos $P$ directamente. Recordemos que las medidas en Alice son $\{ |l\rangle |a_{lk}\rangle \}$, las de Bob son $\{ |m\rangle |a_{mk'}\rangle \}$ y las de Charlie son $\{ | i \rangle| j \rangle \}$.

In [171]:
from codes.Quantum import *

In [172]:
# alpha alpha beta beta gamma gamma
# a     b     b    c    c     a 
# 0     1     2    3    4     5
# -----> 
# gamma alpha beta alpha beta gamma 
# a     a     b     b    c     c
# 5     0     2     1    3     4   

In [173]:
Psi = triple_kron( Psi_ab, Psi_ab, Psi_ab )
Psi = Psi.reshape(6*[2]).transpose([5,0,2,1,4,3]).flatten() 
Rho = np.outer( Psi, Psi.conj() )

In [174]:
Comp_basis = np.eye(2) 

vec_alice = np.zeros( (2,2,4,4) )
for l in range(2):
    for k in range(2):
        operator  = np.kron( Comp_basis[l], M[0,l,k,:] )
        vec_alice[l,k,:,:] = np.outer( operator, operator.conj() )
vec_alice = vec_alice.reshape(4,4,4)

In [175]:
vec_bob = np.zeros( (2,2,4,4) )
for m in range(2):
    for kk in range(2):
        operator = np.kron( Comp_basis[m], M[1,m,kk,:] )
        vec_bob[m,kk,:,:] = np.outer( operator, operator.conj() )
vec_bob = vec_bob.reshape(4,4,4)

In [176]:
Comp_basis = np.array([ 0,1,1,0 ]).reshape(2,2)

vec_charlie = np.zeros( (2,2,4,4) )
for i in range(2):
    for j in range(2):
        operator = np.kron( Comp_basis[i], Comp_basis[j] )
        vec_charlie[i,j,:,:] = np.outer( operator, operator.conj() ) 
vec_charlie = vec_charlie.reshape(4,4,4)

In [177]:
probs_direct = InnerProductMatrices( Rho, 
                                    [ vec_alice, 
                                        vec_bob, 
                                        vec_charlie] 
                                    ).real.reshape(2,2,2,2,2,2)

In [178]:
np.where( np.isclose( probs_direct, (2+np.sqrt(2))/32 ) ) 

(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 1, 1, 0, 0, 1, 1], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1], dtype=int64),
 array([0, 0, 1, 1, 0, 1, 1, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [179]:
np.sum( np.array(probs_direct) - np.array(probs_triangle) )

-3.0531133177191805e-16

Wagon-Wheel Inequality 

In [180]:
probs = probs_direct
probs_albl = np.sum( probs, axis=(1,3,4,5) )
probs_alblclcr = np.sum( probs, axis=(1,3) )
probs_clcr = np.sum( probs, axis=(0,1,2,3) )

In [181]:
inequality = (-probs_albl[1,0] 
                +probs_alblclcr[1,0,1,0] 
                -probs_albl[0,1] * probs_clcr[1,0] 
                -probs_clcr[0,0] * probs_clcr[1,1] 
                -probs_clcr[0,1] * probs[1,0,0,1,1,0]
                -probs_clcr[0,1] * probs[1,1,0,0,1,0]
                +probs_clcr[0,0] * probs[1,0,1,1,1,1]
                +probs_clcr[0,0] * probs[1,1,1,0,1,1]
                +probs_clcr[1,0] * probs[0,0,1,0,0,1]
                +probs_clcr[1,0] * probs[0,1,1,1,0,1]
                +probs_clcr[1,1] * probs[0,0,0,0,0,0]
                +probs_clcr[1,1] * probs[0,1,0,1,0,0]
                )

In [182]:
inequality, (np.sqrt(2)-1)/16 

(0.02588834764831842, 0.025888347648318447)